# Cloudflare Pages 配置 — WallstreetProject

# 项目名
name = "wallstreet"
compatibility_date = "2024-06-01"
pages_build_output_dir = "client/build/web"

[vars]
PYTHON_API_URL = "https://wallstreet-python.onrender.com"
